version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 3.1

  pre_build:
    commands:
      - dotnet restore

  build:
    commands:
      - dotnet build --configuration Release

  post_build:
    commands:
      - dotnet publish -c Release -o ./publish_output

artifacts:
  files: ./publish_output/**
  base-directory: ./publish_output
